name: Render Site

on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: npm run build
      - run: cd site && quarto render
